spring:
  application:
    name: msg-gateway
  redis:
    database: 0
    host: redis
    port: 6379

server:
  port: 8010

sms:
  baseUrl: "http://mock-sms-server:8080"
  sendSms: "/v2/emp/templateSms/sendSms"
  reset: "/v2/emp/templateSms/reset"
  currentStatus: "/v2/emp/templateSms/currentStatus"
