spring:
  application:
    name: msg-gateway
  redis:
    database: 0
    host: localhost
    port: 6379

server:
  port: 8081

sms:
  baseUrl: "http://localhost:8080"
  sendSms: "/v2/emp/templateSms/sendSms"
  reset: "/v2/emp/templateSms/reset"
  currentStatus: "/v2/emp/templateSms/currentStatus"
